# Generated by Django 4.2.5 on 2023-10-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn.dribbble.com/users/1515327/screenshots/4328124/cooking_loader_2_still.gif?resize=400x0', max_length=500),
        ),
    ]
